/**
 * HRManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { Employee } from './employee';


export interface Absence { 
    absenceID?: number;
    employeeID: number;
    description?: string | null;
    startDate: string;
    endDate: string;
    status: Status;
    rejectionReason?: string | null;
    employee?: Employee;
}
export namespace Absence {
}


