/**
 * API IP32
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';


export interface AbsencesEmployeeResponse { 
    firstName?: string | null;
    lastName?: string | null;
    description?: string | null;
    startDate?: string;
    endDate?: string;
    status?: Status;
    rejectionReason?: string | null;
}
export namespace AbsencesEmployeeResponse {
}


