/**
 * API IP32
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileResponse } from './file-response';
import { Role } from './role';


export interface AccountEmployeeResponse { 
    accountID?: number;
    employeeID?: number;
    username?: string | null;
    password?: string | null;
    accountType?: Role;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phone?: string | null;
    country?: string | null;
    city?: string | null;
    street?: string | null;
    postalCode?: string | null;
    photo?: FileResponse;
    dateOfEmployment?: string;
}
export namespace AccountEmployeeResponse {
}


