/**
 * HRManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Position } from './position';
import { Report } from './report';
import { Absence } from './absence';
import { Photo } from './photo';
import { Team } from './team';
import { Document } from './document';


export interface Employee { 
    employeeID?: number;
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    country: string;
    city: string;
    street: string;
    postalCode: string;
    dateOfEmployment: string;
    positionID: number;
    teamID: number;
    position?: Position;
    team?: Team;
    account?: Account;
    photo?: Photo;
    documents?: Array<Document> | null;
    absences?: Array<Absence> | null;
    authoredReports?: Array<Report> | null;
    reportsAboutEmployee?: Array<Report> | null;
}

