/**
 * HRManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Photo } from './photo';


export interface EmployeePositionTeamResponse { 
    employeeID?: number;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phone?: string | null;
    country?: string | null;
    city?: string | null;
    street?: string | null;
    postalCode?: string | null;
    dateOfEmployment?: string;
    positionName?: string | null;
    positionDescription?: string | null;
    teamName?: string | null;
    teamDescription?: string | null;
    department?: string | null;
    photo?: Photo;
}

