/**
 * API IP32
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileResponse } from './file-response';


export interface EmployeePositionTeamResponse { 
    employeeID?: number;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phone?: string | null;
    country?: string | null;
    city?: string | null;
    street?: string | null;
    postalCode?: string | null;
    dateOfEmployment?: string;
    positionID?: number;
    positionName?: string | null;
    positionDescription?: string | null;
    teamID?: number;
    teamName?: string | null;
    teamDescription?: string | null;
    departmentName?: string | null;
    photo?: FileResponse;
}

