/**
 * API IP32
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Role = 'Admin' | 'HR' | 'Employee';

export const Role = {
    Admin: 'Admin' as Role,
    Hr: 'HR' as Role,
    Employee: 'Employee' as Role
};

