/**
 * HRManager.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Severity = 0 | 1 | 2 | 3 | 4;

export const Severity = {
    NUMBER_0: 0 as Severity,
    NUMBER_1: 1 as Severity,
    NUMBER_2: 2 as Severity,
    NUMBER_3: 3 as Severity,
    NUMBER_4: 4 as Severity
};

