/**
 * API IP32
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Severity = 'Cosmetic' | 'Minor' | 'Moderate' | 'Major' | 'Critical';

export const Severity = {
    Cosmetic: 'Cosmetic' as Severity,
    Minor: 'Minor' as Severity,
    Moderate: 'Moderate' as Severity,
    Major: 'Major' as Severity,
    Critical: 'Critical' as Severity
};

