/**
 * API IP32
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Department } from './department';
import { Employee } from './employee';


export interface Team { 
    teamID?: number;
    teamName: string;
    departmentID?: number;
    teamDescription?: string | null;
    employees?: Array<Employee> | null;
    department?: Department;
}

