export * from './absence.api';
import { AbsenceApi } from './absence.api';
export * from './account.api';
import { AccountApi } from './account.api';
export * from './department.api';
import { DepartmentApi } from './department.api';
export * from './document.api';
import { DocumentApi } from './document.api';
export * from './employee.api';
import { EmployeeApi } from './employee.api';
export * from './login.api';
import { LoginApi } from './login.api';
export * from './photo.api';
import { PhotoApi } from './photo.api';
export * from './position.api';
import { PositionApi } from './position.api';
export * from './report.api';
import { ReportApi } from './report.api';
export * from './team.api';
import { TeamApi } from './team.api';
export const APIS = [AbsenceApi, AccountApi, DepartmentApi, DocumentApi, EmployeeApi, LoginApi, PhotoApi, PositionApi, ReportApi, TeamApi];
